[package]
name = "rustrimeitor"
version = "0.1.0"
authors = ["Emilio Wuerges <wuerges@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
clap = "2.33.3"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

[dependencies.server]
path = "server"

[dependencies.data]
path = "data"

[workspace]
members = [
    "server",
    # "client",
    # "turbineitor",
    # "turbineitor/ui",
    "data",
]

[profile.release.package.client]
opt-level = 'z'
codegen-units = 1
