version: "3.7"
services:
  animeitor:
    image: animeitor
    command: "/simples --config $SEDES --secret $SECRET $BOCA_URL --port $HTTP_PORT --public $HTTP_PORT"
    build: 
      context: .
      args:
        - DOCKER_BUILDKIT=1
        - HTTP_PORT=$HTTP_PORT
    ports: 
      - $HTTP_PORT:$HTTP_PORT
    volumes:
      - ./photos:/photos
      - ./tests:/tests
      - ./config:/config


