args: config/ICPC_LA_2022_secret.toml
salt = "gdhd"

[[secrets]]
name = "North"
secret = "TLJP"

[[secrets]]
name = "Venezuela"
secret = "6ct0"

[[secrets]]
name = "Colombia"
secret = "kGdz"

[[secrets]]
name = "South"
secret = "MrIt"

[[secrets]]
name = "Argentina"
secret = "yksQ"

[[secrets]]
name = "Bolivia"
secret = "lcJ6"

[[secrets]]
name = "Chile"
secret = "OoR7"

[[secrets]]
name = "Peru"
secret = "ZZ71"

[[secrets]]
name = "Brasil"
secret = "4KGf"

[[secrets]]
name = "Mexico"
secret = "8ItD"

[[secrets]]
name = "Central America"
secret = "ClYk"

[[secrets]]
name = "El Salvador"
secret = "zHWI"

[[secrets]]
name = "Costa Rica"
secret = "cOHv"

[[secrets]]
name = "Caribe"
secret = "ndP4"

[[secrets]]
name = "Cuba"
secret = "ImE8"

[[secrets]]
name = "Republica Dominicana"
secret = "mUto"

[[secrets]]
name = "Puerto Rico"
secret = "2UpE"

[[secrets]]
name = "Latin America"
secret = "kIv8"

