[tasks.watch]
description = "Watch files and recompile the project on change"
run_task = []

[tasks.watch_server]
description = "Watch files and recompile the project on change"
run_task = []

[tasks.build_release]
description = "Dummy task"
run_task = []
