[package]
name = "server"
version = "0.3.0"
authors = ["Emilio Wuerges <wuerges@gmail.com>"]
edition = "2021"

[features]
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.27", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
itertools = "0.10"
toml = "0.7"
futures = "0.3"
html-escape = "0.2"
parking_lot = "0.12"
service = { path = "../service" }
thiserror = "1.0"
warp-embed = "0.4"
rust-embed = "6.6"
openssl = { version = "0.10", features = ["vendored"] }
sentry = "0.30.0"
autometrics = { version = "0.2.4", features = [
    "prometheus-exporter",
    "metrics",
] }
prometheus = { version = "0.13.3", features = ["process"] }
metrics = "0.20.1"
metrics-prometheus = "0.3.1"

[dependencies.data]
path = "../data"
