titulo = "ICPC Latin America Regional Contest"

# br - Brasil
[[sedes]]
name="Brasil"
premiacao=true
vagas=5
codes=[
  "teambr"
]
ouro = 3
prata = 6
bronze = 10

# so - South
[[sedes]]
name="South"
premiacao=false
vagas=5
codes=[
  "teamso"
]
ouro = 3
prata = 6
bronze = 10

# no - North
[[sedes]]
name="North"
premiacao=false
vagas=5
codes=[
  "teamno"
]
ouro = 3
prata = 6
bronze = 10

# ca - Central America
[[sedes]]
name="Central America"
premiacao=false
vagas=5
codes=[
  "teamca"
]
ouro = 3
prata = 6
bronze = 10

# cb - Caribe
[[sedes]]
name="Caribe"
premiacao=false
vagas=5
codes=[
  "teamcb"
]
ouro = 1
prata = 2
bronze = 3

# mx - Mexico
[[sedes]]
name="Mexico"
premiacao=false
vagas=5
codes=[
  "teammx"
]
ouro = 3
prata = 6
bronze = 10

[[sedes]]
name="Latin America"
codes=["team"]
premiacao=false
vagas=0
ouro = 3
prata = 6
bronze = 10
