titulo = "Maratona de Programação da SBC - 1ª fase"

[[sedes]]
name="Acre"
codes=["teambrac"]
premiacao=false
vagas=0

[[sedes]]
name="Alagoas"
codes=["teambral"]
premiacao=false
vagas=0

[[sedes]]
name="Amazonas"
codes=["teambram"]
premiacao=true
vagas=1

[[sedes]]
name="Amapá"
codes=["teambrap"]
premiacao=true
vagas=1

[[sedes]]
name="Bahia"
codes=["teambrba"]
premiacao=true
vagas=2

[[sedes]]
name="Ceará"
codes=["teambrce"]
premiacao=true
vagas=3

[[sedes]]
name="Distrito Federal"
codes=["teambrdf"]
premiacao=true
vagas=1

[[sedes]]
name="Espírito Santo"
codes=["teambres"]
premiacao=true
vagas=1

[[sedes]]
name="Goiás"
codes=["teambrgo"]
premiacao=true
vagas=1

[[sedes]]
name="Maranhão"
codes=["teambrma"]
premiacao=false
vagas=0

[[sedes]]
name="Minas Gerais"
codes=["teambrmg"]
premiacao=true
vagas=6

[[sedes]]
name="Mato Grosso do Sul"
codes=["teambrms"]
premiacao=false
vagas=0

[[sedes]]
name="Mato Grosso"
codes=["teambrmt"]
premiacao=false
vagas=0

[[sedes]]
name="Pará"
codes=["teambrpa"]
premiacao=false
vagas=0

[[sedes]]
name="Paraíba"
codes=["teambrpb"]
premiacao=true
vagas=1

[[sedes]]
name="Pernambuco"
codes=["teambrpe"]
premiacao=false
vagas=0

[[sedes]]
name="Piauí"
codes=["teambrpi"]
premiacao=false
vagas=0

[[sedes]]
name="Paraná"
codes=["teambrpr"]
premiacao=true
vagas=2

[[sedes]]
name="Rio de Janeiro"
codes=["teambrrj"]
premiacao=true
vagas=2

[[sedes]]
name="Rio Grande do Norte"
codes=["teambrrn"]
premiacao=false
vagas=0

[[sedes]]
name="Rondônia"
codes=["teambrro"]
premiacao=false
vagas=0

[[sedes]]
name="Roraima"
codes=["teambrrr"]
premiacao=false
vagas=0

[[sedes]]
name="Rio Grande do Sul"
codes=["teambrrs"]
premiacao=true
vagas=1

[[sedes]]
name="Santa Catarina"
codes=["teambrsc"]
premiacao=true
vagas=3

[[sedes]]
name="Sergipe"
codes=["teambrse"]
premiacao=false
vagas=0

[[sedes]]
name="São Paulo"
codes=["teambrsp"]
premiacao=true
vagas=8

[[sedes]]
name="Tocantins"
codes=["teambrto"]
premiacao=false
vagas=0

[[sedes]]
name="Supersede Centro-Oeste"
premiacao=true
vagas=1
codes=[
  "teambrmt",
  "teambrms",
]

[[sedes]]
name="Supersede Nordeste"
premiacao=true
vagas=2
codes=[
  "teambral",
  "teambrma",
  "teambrpe",
  "teambrrn",
  "teambrse",
]

[[sedes]]
name="Supersede Norte"
premiacao=true
vagas=2
codes=[
  "teambrac",
  "teambrpa",
  "teambrro",
  "teambrrr",
  "teambrto",
]

[[sedes]]
name="Brasil"
codes=["teambr"]
premiacao=false
vagas=0

[[escolas]]
codigo="cefet-mg"
imagem="cefet-mg.png"
nome="cefet-mg"

[[escolas]]
codigo="cefet-rj"
imagem="cefet-rj.png"
nome="cefet-rj"

[[escolas]]
codigo="fatec-sorocaba"
imagem="fatec-sorocaba.jpg"
nome="fatec-sorocaba"

[[escolas]]
codigo="ifceara"
imagem="ifceara.png"
nome="ifceara"

[[escolas]]
codigo="ifpb-joaopessoa"
imagem="ifpb-joaopessoa.png"
nome="ifpb-joaopessoa"

[[escolas]]
codigo="ifsp"
imagem="ifsp.png"
nome="ifsp"

[[escolas]]
codigo="ifsuldeminas"
imagem="ifsuldeminas.png"
nome="ifsuldeminas"

[[escolas]]
codigo="ime"
imagem="ime.jpg"
nome="ime"

[[escolas]]
codigo="inatel"
imagem="inatel.jpg"
nome="inatel"

[[escolas]]
codigo="ita"
imagem="ita.png"
nome="ita"

[[escolas]]
codigo="puc-goias"
imagem="puc-goias.jpg"
nome="puc-goias"

[[escolas]]
codigo="puc-rio"
imagem="puc-rio.jpg"
nome="puc-rio"

[[escolas]]
codigo="udesc"
imagem="udesc.png"
nome="udesc"

[[escolas]]
codigo="uea"
imagem="uea.png"
nome="uea"

[[escolas]]
codigo="uece"
imagem="uece.png"
nome="uece"

[[escolas]]
codigo="uefs"
imagem="uefs.jpg"
nome="uefs"

[[escolas]]
codigo="uesb"
imagem="uesb.jpg"
nome="uesb"

[[escolas]]
codigo="ufabc"
imagem="ufabc.png"
nome="ufabc"

[[escolas]]
codigo="ufac"
imagem="ufac.png"
nome="ufac"

[[escolas]]
codigo="ufal-arapiraca"
imagem="ufal-arapiraca.png"
nome="ufal-arapiraca"

[[escolas]]
codigo="ufal"
imagem="ufal.png"
nome="ufal"

[[escolas]]
codigo="ufam"
imagem="ufam.jpg"
nome="ufam"

[[escolas]]
codigo="ufba"
imagem="ufba.jpg"
nome="ufba"

[[escolas]]
codigo="ufce"
imagem="ufce.jpg"
nome="ufce"

[[escolas]]
codigo="ufce-quixada"
imagem="ufce-quixada.png"
nome="ufce-quixada"

[[escolas]]
codigo="ufcg"
imagem="ufcg.png"
nome="ufcg"

[[escolas]]
codigo="ufes"
imagem="ufes.png"
nome="ufes"

[[escolas]]
codigo="ufg"
imagem="ufg.png"
nome="ufg"

[[escolas]]
codigo="ufma"
imagem="ufma.jpg"
nome="ufma"

[[escolas]]
codigo="ufmg"
imagem="ufmg.png"
nome="ufmg"

[[escolas]]
codigo="ufms"
imagem="ufms.png"
nome="ufms"

[[escolas]]
codigo="ufmt"
imagem="ufmt.jpg"
nome="ufmt"

[[escolas]]
codigo="ufpa"
imagem="ufpa.png"
nome="ufpa"

[[escolas]]
codigo="ufpe"
imagem="ufpe.jpg"
nome="ufpe"

[[escolas]]
codigo="ufpi"
imagem="ufpi.jpg"
nome="ufpi"

[[escolas]]
codigo="ufpr"
imagem="ufpr.jpg"
nome="ufpr"

[[escolas]]
codigo="ufrgs"
imagem="ufrgs.png"
nome="ufrgs"

[[escolas]]
codigo="ufrj"
imagem="ufrj.jpg"
nome="ufrj"

[[escolas]]
codigo="ufrn"
imagem="ufrn.png"
nome="ufrn"

[[escolas]]
codigo="ufrr"
imagem="ufrr.png"
nome="ufrr"

[[escolas]]
codigo="ufscar"
imagem="ufscar.png"
nome="ufscar"

[[escolas]]
codigo="ufsc"
imagem="ufsc.png"
nome="ufsc"

[[escolas]]
codigo="ufs"
imagem="ufs.png"
nome="ufs"

[[escolas]]
codigo="ufu"
imagem="ufu.png"
nome="ufu"

[[escolas]]
codigo="ufv-florestal"
imagem="ufv-florestal.png"
nome="ufv-florestal"

[[escolas]]
codigo="ufv"
imagem="ufv.jpg"
nome="ufv"

[[escolas]]
codigo="unb-gama"
imagem="unb-gama.jpg"
nome="unb-gama"

[[escolas]]
codigo="unb"
imagem="unb.png"
nome="unb"

[[escolas]]
codigo="unesc"
imagem="unesc.jpg"
nome="unesc"

[[escolas]]
codigo="unesp"
imagem="unesp.png"
nome="unesp"

[[escolas]]
codigo="unicamp"
imagem="unicamp.png"
nome="unicamp"

[[escolas]]
codigo="unifap"
imagem="unifap.png"
nome="unifap"

[[escolas]]
codigo="unifei"
imagem="unifei.png"
nome="unifei"

[[escolas]]
codigo="unir"
imagem="unir.png"
nome="unir"

[[escolas]]
codigo="univem"
imagem="univem.jpg"
nome="univem"

[[escolas]]
codigo="unoeste"
imagem="unoeste.png"
nome="unoeste"

[[escolas]]
codigo="usp"
imagem="usp.png"
nome="usp"

[[escolas]]
codigo="usp-sc"
imagem="usp-sc.png"
nome="usp-sc"

[[escolas]]
codigo="utfpr"
imagem="utfpr.png"
nome="utfpr"
