titulo = "Maratona de Programação da SBC - 1ª fase"

[[sedes]]
name="Acre"
codes=["teambrac"]
premiacao=false
vagas=0

[[sedes]]
name="Alagoas"
codes=["teambral"]
premiacao=false
vagas=0

[[sedes]]
name="Amazonas"
codes=["teambram"]
premiacao=true
vagas=1

[[sedes]]
name="Amapá"
codes=["teambrap"]
premiacao=true
vagas=1

[[sedes]]
name="Bahia"
codes=["teambrba"]
premiacao=true
vagas=2

[[sedes]]
name="Ceará"
codes=["teambrce"]
premiacao=true
vagas=3

[[sedes]]
name="Distrito Federal"
codes=["teambrdf"]
premiacao=true
vagas=1

[[sedes]]
name="Espírito Santo"
codes=["teambres"]
premiacao=true
vagas=1

[[sedes]]
name="Goiás"
codes=["teambrgo"]
premiacao=true
vagas=1

[[sedes]]
name="Maranhão"
codes=["teambrma"]
premiacao=false
vagas=0

[[sedes]]
name="Minas Gerais"
codes=["teambrmg"]
premiacao=true
vagas=6

[[sedes]]
name="Mato Grosso do Sul"
codes=["teambrms"]
premiacao=false
vagas=0

[[sedes]]
name="Mato Grosso"
codes=["teambrmt"]
premiacao=false
vagas=0

[[sedes]]
name="Pará"
codes=["teambrpa"]
premiacao=false
vagas=0

[[sedes]]
name="Paraíba"
codes=["teambrpb"]
premiacao=true
vagas=1

[[sedes]]
name="Pernambuco"
codes=["teambrpe"]
premiacao=false
vagas=0

[[sedes]]
name="Piauí"
codes=["teambrpi"]
premiacao=false
vagas=0

[[sedes]]
name="Paraná"
codes=["teambrpr"]
premiacao=true
vagas=2

[[sedes]]
name="Rio de Janeiro"
codes=["teambrrj"]
premiacao=true
vagas=2

[[sedes]]
name="Rio Grande do Norte"
codes=["teambrrn"]
premiacao=false
vagas=0

[[sedes]]
name="Rondônia"
codes=["teambrro"]
premiacao=false
vagas=0

[[sedes]]
name="Roraima"
codes=["teambrrr"]
premiacao=false
vagas=0

[[sedes]]
name="Rio Grande do Sul"
codes=["teambrrs"]
premiacao=true
vagas=1

[[sedes]]
name="Santa Catarina"
codes=["teambrsc"]
premiacao=true
vagas=3

[[sedes]]
name="Sergipe"
codes=["teambrse"]
premiacao=false
vagas=0

[[sedes]]
name="São Paulo"
codes=["teambrsp"]
premiacao=true
vagas=8

[[sedes]]
name="Tocantins"
codes=["teambrto"]
premiacao=false
vagas=0

[[sedes]]
name="Supersede Centro-Oeste"
premiacao=true
vagas=1
codes=[
  "teambrmt",
  "teambrms",
]

[[sedes]]
name="Supersede Nordeste"
premiacao=true
vagas=2
codes=[
  "teambral",
  "teambrma",
  "teambrpe",
  "teambrrn",
  "teambrse",
]

[[sedes]]
name="Supersede Norte"
premiacao=true
vagas=2
codes=[
  "teambrac",
  "teambrpa",
  "teambrro",
  "teambrrr",
  "teambrto",
]

[[sedes]]
name="Brasil"
codes=["teambr"]
premiacao=false
vagas=0

[[escolas]]
code="cefet-mg"
logo="cefet-mg.png"
name="cefet-mg"

[[escolas]]
code="cefet-rj"
logo="cefet-rj.png"
name="cefet-rj"

[[escolas]]
code="fatec-sorocaba"
logo="fatec-sorocaba.jpg"
name="fatec-sorocaba"

[[escolas]]
code="ifceara"
logo="ifceara.png"
name="ifceara"

[[escolas]]
code="ifpb-joaopessoa"
logo="ifpb-joaopessoa.png"
name="ifpb-joaopessoa"

[[escolas]]
code="ifsp"
logo="ifsp.png"
name="ifsp"

[[escolas]]
code="ifsuldeminas"
logo="ifsuldeminas.png"
name="ifsuldeminas"

[[escolas]]
code="ime"
logo="ime.jpg"
name="ime"

[[escolas]]
code="inatel"
logo="inatel.jpg"
name="inatel"

[[escolas]]
code="ita"
logo="ita.png"
name="ita"

[[escolas]]
code="puc-goias"
logo="puc-goias.jpg"
name="puc-goias"

[[escolas]]
code="puc-rio"
logo="puc-rio.jpg"
name="puc-rio"

[[escolas]]
code="udesc"
logo="udesc.png"
name="udesc"

[[escolas]]
code="uea"
logo="uea.png"
name="uea"

[[escolas]]
code="uece"
logo="uece.png"
name="uece"

[[escolas]]
code="uefs"
logo="uefs.jpg"
name="uefs"

[[escolas]]
code="uesb"
logo="uesb.jpg"
name="uesb"

[[escolas]]
code="ufabc"
logo="ufabc.png"
name="ufabc"

[[escolas]]
code="ufac"
logo="ufac.png"
name="ufac"

[[escolas]]
code="ufal-arapiraca"
logo="ufal-arapiraca.png"
name="ufal-arapiraca"

[[escolas]]
code="ufal"
logo="ufal.png"
name="ufal"

[[escolas]]
code="ufam"
logo="ufam.jpg"
name="ufam"

[[escolas]]
code="ufba"
logo="ufba.jpg"
name="ufba"

[[escolas]]
code="ufce"
logo="ufce.jpg"
name="ufce"

[[escolas]]
code="ufce-quixada"
logo="ufce-quixada.png"
name="ufce-quixada"

[[escolas]]
code="ufcg"
logo="ufcg.png"
name="ufcg"

[[escolas]]
code="ufes"
logo="ufes.png"
name="ufes"

[[escolas]]
code="ufg"
logo="ufg.png"
name="ufg"

[[escolas]]
code="ufma"
logo="ufma.jpg"
name="ufma"

[[escolas]]
code="ufmg"
logo="ufmg.png"
name="ufmg"

[[escolas]]
code="ufms"
logo="ufms.png"
name="ufms"

[[escolas]]
code="ufmt"
logo="ufmt.jpg"
name="ufmt"

[[escolas]]
code="ufpa"
logo="ufpa.png"
name="ufpa"

[[escolas]]
code="ufpe"
logo="ufpe.jpg"
name="ufpe"

[[escolas]]
code="ufpi"
logo="ufpi.jpg"
name="ufpi"

[[escolas]]
code="ufpr"
logo="ufpr.jpg"
name="ufpr"

[[escolas]]
code="ufrgs"
logo="ufrgs.png"
name="ufrgs"

[[escolas]]
code="ufrj"
logo="ufrj.jpg"
name="ufrj"

[[escolas]]
code="ufrn"
logo="ufrn.png"
name="ufrn"

[[escolas]]
code="ufrr"
logo="ufrr.png"
name="ufrr"

[[escolas]]
code="ufscar"
logo="ufscar.png"
name="ufscar"

[[escolas]]
code="ufsc"
logo="ufsc.png"
name="ufsc"

[[escolas]]
code="ufs"
logo="ufs.png"
name="ufs"

[[escolas]]
code="ufu"
logo="ufu.png"
name="ufu"

[[escolas]]
code="ufv-florestal"
logo="ufv-florestal.png"
name="ufv-florestal"

[[escolas]]
code="ufv"
logo="ufv.jpg"
name="ufv"

[[escolas]]
code="unb-gama"
logo="unb-gama.jpg"
name="unb-gama"

[[escolas]]
code="unb"
logo="unb.png"
name="unb"

[[escolas]]
code="unesc"
logo="unesc.jpg"
name="unesc"

[[escolas]]
code="unesp"
logo="unesp.png"
name="unesp"

[[escolas]]
code="unicamp"
logo="unicamp.png"
name="unicamp"

[[escolas]]
code="unifap"
logo="unifap.png"
name="unifap"

[[escolas]]
code="unifei"
logo="unifei.png"
name="unifei"

[[escolas]]
code="unir"
logo="unir.png"
name="unir"

[[escolas]]
code="univem"
logo="univem.jpg"
name="univem"

[[escolas]]
code="unoeste"
logo="unoeste.png"
name="unoeste"

[[escolas]]
code="usp"
logo="usp.png"
name="usp"

[[escolas]]
code="usp-sc"
logo="usp-sc.png"
name="usp-sc"

[[escolas]]
code="utfpr"
logo="utfpr.png"
name="utfpr"
