[[teams]]
login="arq1"
nome="Nome do Config"
foto="KLM.png"
musica="https://youtu.be/gdG4xbU8cZo"
comentario="Na foto: Prof. Acauan (Coach), Markus Kaul, Leandro Schillreff, Miller Raycell"

[[teams]]
login="teambrsp066"
nome="Time Fake"
foto="fake.png"
musica="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
comentario="Este time e' falso, mas a musica e' legal"

[[teams]]
login = "teambrbr01"
nome = "Hoje tem AC do Ribamar"
foto = "teambrbr01.png"

[[teams]]
login = "teambrbr02"
nome = "KLM"
foto = "teambrbr02.png"

[[teams]]
login = "teambrbr03"
nome = "Vêm tranquilo, afoba não"
foto = "teambrbr03.png"

[[teams]]
login = "teambrbr04"
nome = "cuscuz com cachaça"
foto = "teambrbr04.png"

[[teams]]
login = "teambrbr05"
nome = "Os k-ésimos"
foto = "teambrbr05.png"

[[teams]]
login = "teambrbr06"
nome = "Xerebêlerebébis"
foto = "teambrbr06.png"

[[teams]]
login = "teambrbr07"
nome = "Que bixiga é essa?"
foto = "teambrbr07.png"

[[teams]]
login = "teambrbr08"
nome = "UnespRPM"
foto = "teambrbr08.png"

[[teams]]
login = "teambrbr09"
nome = "anarquia às 8"
foto = "teambrbr09.png"

[[teams]]
login = "teambrbr10"
nome = "Você é fraco, te falta O(1)"
foto = "teambrbr10.png"

[[teams]]
login = "teambrbr11"
nome = "AC(¬‿¬)WA"
foto = "teambrbr11.png"

[[teams]]
login = "teambrbr12"
nome = "Monkeys"
foto = "teambrbr12.png"

[[teams]]
login = "teambrbr13"
nome = "União Fiasco"
foto = "teambrbr13.png"

[[teams]]
login = "teambrbr14"
nome = "Sem TLE irmão"
foto = "teambrbr14.png"

[[teams]]
login = "teambrbr15"
nome = "NP-Lúcia"
foto = "teambrbr15.png"

[[teams]]
login = "teambrbr16"
nome = "Mews Lovers"
foto = "teambrbr16.png"

[[teams]]
login = "teambrbr17"
nome = "Wrong Answer 1000%"
foto = "teambrbr17.png"

[[teams]]
login = "teambrbr18"
nome = "UFMA Time 1"
foto = "teambrbr18.png"

[[teams]]
login = "teambrbr19"
nome = "EM3.1415NA"
foto = "teambrbr19.png"

[[teams]]
login = "teambrbr20"
nome = "Três caras numa moto"
foto = "teambrbr20.png"

[[teams]]
login = "teambrbr21"
nome = "Programadores: continue"
foto = "teambrbr21.png"

[[teams]]
login = "teambrbr22"
nome = "KondZhiLa"
foto = "teambrbr22.png"

[[teams]]
login = "teambrbr23"
nome = "[nome_do_time]"
foto = "teambrbr23.png"

[[teams]]
login = "teambrbr24"
nome = "Dorime"
foto = "teambrbr24.png"

[[teams]]
login = "teambrbr25"
nome = "Qual o nome do time?"
foto = "teambrbr25.png"

[[teams]]
login = "teambrbr26"
nome = "namae wa??"
foto = "teambrbr26.png"

[[teams]]
login = "teambrbr27"
nome = "vae victis"
foto = "teambrbr27.png"

[[teams]]
login = "teambrbr28"
nome = "Quero café"
foto = "teambrbr28.png"

[[teams]]
login = "teambrbr29"
nome = "O amarelo é impostor"
foto = "teambrbr29.png"

[[teams]]
login = "teambrbr30"
nome = "$wa"
foto = "teambrbr30.png"

[[teams]]
login = "teambrbr31"
nome = "GTA: Grover's Street Algorithms"
foto = "teambrbr31.png"

[[teams]]
login = "teambrbr32"
nome = "O(f*ck)"
foto = "teambrbr32.png"

[[teams]]
login = "teambrbr33"
nome = "A query tá on"
foto = "teambrbr33.png"

[[teams]]
login = "teambrbr34"
nome = "Rock Lee Casado Não Vai + Pra Pagode"
foto = "teambrbr34.png"

[[teams]]
login = "teambrbr35"
nome = "GGG"
foto = "teambrbr35.png"

[[teams]]
login = "teambrbr36"
nome = "Beto was ejected"
foto = "teambrbr36.png"

[[teams]]
login = "teambrbr37"
nome = "YouShallNot.stay"
foto = "teambrbr37.png"

[[teams]]
login = "teambrbr38"
nome = "RGB IFSP-ARQ Team"
foto = "teambrbr38.png"

[[teams]]
login = "teambrbr39"
nome = "Amigos da Aracele"
foto = "teambrbr39.png"

[[teams]]
login = "teambrbr40"
nome = "PD pá"
foto = "teambrbr40.png"

[[teams]]
login = "teambrbr41"
nome = "Bagre Branco, Branco Bagre"
foto = "teambrbr41.png"

[[teams]]
login = "teambrbr42"
nome = "WA em O(1)"
foto = "teambrbr42.png"

[[teams]]
login = "teambrbr43"
nome = "BalloonField"
foto = "teambrbr43.png"

[[teams]]
login = "teambrbr44"
nome = "2 matemáticos e 2 flamenguistas"
foto = "teambrbr44.png"

[[teams]]
login = "teambrbr45"
nome = "Mensageiros do à main"
foto = "teambrbr45.png"

[[teams]]
login = "teambrbr46"
nome = "Que time?"
foto = "teambrbr46.png"

[[teams]]
login = "teambrbr47"
nome = ":ultra_fast_parrot:"
foto = "teambrbr47.png"

[[teams]]
login = "teambrbr48"
nome = "Abacate Atômico"
foto = "teambrbr48.png"

[[teams]]
login = "teambrbr49"
nome = "Vamu vense"
foto = "teambrbr49.png"

[[teams]]
login = "teambrbr50"
nome = "man java"
foto = "teambrbr50.png"

[[teams]]
login = "teambrbr51"
nome = "Code Zwang"
foto = "teambrbr51.png"

[[teams]]
login = "teambrbr52"
nome = "NP-Compeixe"
foto = "teambrbr52.png"

[[teams]]
login = "teambrbr53"
nome = "Home Off C++"
foto = "teambrbr53.png"

[[teams]]
login = "teambrbr54"
nome = "Code Distancing"
foto = "teambrbr54.png"

[[teams]]
login = "teambrbr55"
nome = "Overclock"
foto = "teambrbr55.png"

[[teams]]
login = "teambrbr56"
nome = "No Main No Gain"
foto = "teambrbr56.png"

[[teams]]
login = "teambrbr57"
nome = "deitando no gramado"
foto = "teambrbr57.png"

[[teams]]
login = "teambrbr58"
nome = "CPA - Carregados Pelo Alyson"
foto = "teambrbr58.png"

[[teams]]
login = "teambrbr59"
nome = "Bolonhesa"
foto = "teambrbr59.png"

[[teams]]
login = "teambrbr60"
nome = "S -> aSa | a"
foto = "teambrbr60.png"

[[teams]]
login = "teambrbr61"
nome = "Alquimistas"
foto = "teambrbr61.png"

[[teams]]
login = "teambrbr62"
nome = "seila"
foto = "teambrbr62.png"

[[teams]]
login = "teambrbr63"
nome = "The droids you are looking for"
foto = "teambrbr63.png"

[[teams]]
login = "teambrbr64"
nome = "Conexão Tucuju: aqui o caixeiro chegou de barco"
foto = "teambrbr64.png"

