[[teams]]
login = "teambrrr001"
nome = "KLM"
foto = "teambrbr02.webp"
musica= "https://youtu.be/gdG4xbU8cZo"
comentario = "Na foto: Prof. Acauan (Coach), Markus Kaul, Leandro Schillreff, Miller Raycell"

[[teams]]
login="teambrsp066"
nome="Time Fake"
foto="fake.png"
musica="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
comentario="Este time e' falso, mas a musica e' legal"

[[teams]]
login = "teambrbr001"
nome = "Hoje tem AC do Ribamar"
foto = "teambrbr01.webp"
musica = "https://www.youtube.com/watch?v=M1n0s60dL44"

[[teams]]
login = "teambrbr002"
nome = "KLM"
foto = "teambrbr02.webp"
musica= "https://youtu.be/gdG4xbU8cZo"
comentario = "Na foto: Prof. Acauan (Coach), Markus Kaul, Leandro Schillreff, Miller Raycell"

[[teams]]
login = "teambrbr003"
nome = "Vêm tranquilo, afoba não"
foto = "teambrbr03.webp"

[[teams]]
login = "teambrbr004"
nome = "cuscuz com cachaça"
musica = "https://www.youtube.com/watch?v=GqutEnlLX6o"
foto = "teambrbr04.webp"
comentario = "sim"

[[teams]]
login = "teambrbr005"
nome = "Os k-ésimos"
foto = "teambrbr05.webp"
musica = "https://www.youtube.com/watch?v=fB8TyLTD7EE"

[[teams]]
login = "teambrbr006"
nome = "Xerebêlerebébis"
musica = "https://www.youtube.com/watch?v=GsFlbMS7UIc"
foto = "teambrbr06.webp"

[[teams]]
login = "teambrbr007"
nome = "Que bixiga é essa?"
musica = "https://www.youtube.com/watch?v=hIRRx5hYK34"
foto = "teambrbr07.webp"

[[teams]]
login = "teambrbr008"
nome = "UnespRPM"
foto = "teambrbr08.webp"

[[teams]]
login = "teambrbr009"
nome = "anarquia às 8"
foto = "teambrbr09.webp"

[[teams]]
login = "teambrbr010"
nome = "Você é fraco, te falta O(1)"
foto = "teambrbr10.webp"

[[teams]]
login = "teambrbr011"
nome = "AC(¬‿¬)WA"
foto = "teambrbr11.webp"
musica = "https://www.youtube.com/watch?v=CCdw2Adqch0"

[[teams]]
login = "teambrbr012"
nome = "Monkeys"
musica = "https://youtu.be/rBSfI10pXHM"
foto = "teambrbr12.webp"

[[teams]]
login = "teambrbr013"
nome = "União Fiasco"
foto = "teambrbr13.webp"
musica = "https://www.youtube.com/watch?v=OyxbfVpDBCE"

[[teams]]
login = "teambrbr014"
nome = "Sem TLE irmão"
foto = "teambrbr14.webp"

[[teams]]
login = "teambrbr015"
nome = "NP-Lúcia"
foto = "teambrbr15.webp"

[[teams]]
login = "teambrbr016"
nome = "Mews Lovers"
musica = "https://www.youtube.com/watch?v=Akzba3ubOmI"
foto = "teambrbr16.webp"
comentario = "Após anos de hegemonia com um time imbatível, Weiss e Felipera embarcam em uma nova missão ao lado de Gasparini."

[[teams]]
login = "teambrbr017"
nome = "Wrong Answer 1000%"
foto = "teambrbr17.webp"

[[teams]]
login = "teambrbr018"
nome = "UFMA Time 1"
foto = "teambrbr18.webp"
musica = "https://youtu.be/WNeLUngb-Xg"

[[teams]]
login = "teambrbr019"
nome = "EM3.1415NA"
musica = "https://youtu.be/A_EWrzI2CUg"
foto = "teambrbr19.webp"

[[teams]]
login = "teambrbr020"
nome = "Três caras numa moto"
foto = "teambrbr20.webp"

[[teams]]
login = "teambrbr021"
nome = "Programadores: continue"
musica = "https://youtu.be/AYlvRQhYGS4"
foto = "teambrbr21.webp"

[[teams]]
login = "teambrbr022"
nome = "KondZhiLa"
musica = "https://www.youtube.com/watch?v=yQ8xJHuW7TY"
foto = "teambrbr22.webp"

[[teams]]
login = "teambrbr023"
nome = "[nome_do_time]"
foto = "teambrbr23.webp"

[[teams]]
login = "teambrbr024"
nome = "Dorime"
foto = "teambrbr24.webp"

[[teams]]
login = "teambrbr025"
nome = "Qual o nome do time?"
foto = "teambrbr25.webp"

[[teams]]
login = "teambrbr026"
nome = "namae wa??"
musica = "https://www.youtube.com/watch?v=zcL74R3akrk"
foto = "teambrbr26.webp"

[[teams]]
login = "teambrbr027"
nome = "vae victis"
foto = "teambrbr27.webp"

[[teams]]
login = "teambrbr028"
nome = "Quero café"
foto = "teambrbr28.webp"

[[teams]]
login = "teambrbr029"
nome = "O amarelo é impostor"
musica = "https://www.youtube.com/watch?v=qv7LYwC7a4c"
foto = "teambrbr29.webp"

[[teams]]
login = "teambrbr030"
nome = "$wa"
musica = "https://drive.google.com/file/d/1pfyjFWrcNHq6cdk2jtGK6l4xMLUdjWEd/view?usp=sharing"
foto = "teambrbr30.webp"
comentario = "Estamos enviando a música via drive. Se precisar que faça o upload em outra plataforma podemos fazer. Feita com muito carinho, por favor se esforcem para nos encaixar em algum prêmio com música. Brincadeira rs, um abraço."

[[teams]]
login = "teambrbr031"
nome = "GTA: Grover's Street Algorithms"
foto = "teambrbr31.webp"

[[teams]]
login = "teambrbr032"
nome = "O(f*ck)"
foto = "teambrbr32.webp"

[[teams]]
login = "teambrbr033"
nome = "A query tá on"
foto = "teambrbr33.webp"
musica = "https://youtu.be/DXohfR9fF7A"

[[teams]]
login = "teambrbr034"
nome = "Rock Lee Casado Não Vai + Pra Pagode"
foto = "teambrbr34.webp"


[[teams]]
login = "teambrbr035"
nome = "GGG"
foto = "teambrbr35.webp"

[[teams]]
login = "teambrbr036"
nome = "Beto was ejected"
foto = "teambrbr36.webp"

[[teams]]
login = "teambrbr037"
nome = "YouShallNot.stay"
foto = "teambrbr37.webp"
musica = "https://www.youtube.com/watch?v=8CDQ83EBClk"
comentario ="They're taking the hobbits to isengard!"

[[teams]]
login = "teambrbr038"
nome = "RGB IFSP-ARQ Team"
musica = "https://www.youtube.com/watch?v=xAM51Ovpr9M"
foto = "teambrbr38.webp"

[[teams]]
login = "teambrbr039"
nome = "Amigos da Aracele"
musica = "https://www.youtube.com/watch?v=XusBJ8ADSH8"
foto = "teambrbr39.webp"

[[teams]]
login = "teambrbr040"
nome = "PD pá"
foto = "teambrbr40.webp"
musica = "https://www.youtube.com/watch?v=JlqwNvePzOs"

[[teams]]
login = "teambrbr041"
nome = "Bagre Branco, Branco Bagre"
foto = "teambrbr41.webp"
musica = "https://www.youtube.com/watch?v=8cbvC_C9y7Y"

[[teams]]
login = "teambrbr042"
nome = "WA em O(1)"
foto = "teambrbr42.webp"

[[teams]]
login = "teambrbr043"
nome = "BalloonField"
foto = "teambrbr43.webp"

[[teams]]
login = "teambrbr044"
nome = "2 matemáticos e 2 flamenguistas"
musica = "https://www.youtube.com/watch?v=kDs_P1ek5cE"
foto = "teambrbr44.webp"

[[teams]]
login = "teambrbr045"
nome = "Mensageiros do à main"
foto = "teambrbr45.webp"

[[teams]]
login = "teambrbr046"
nome = "Que time?"
foto = "teambrbr46.webp"

[[teams]]
login = "teambrbr047"
nome = ":ultra_fast_parrot:"
musica = "https://www.youtube.com/watch?v=kAdbOO6xWkc"
foto = "teambrbr47.webp"
comentario = """De cima para baixo e da esquerda para direita na foto:
- Prof. Wladimir Tavares
- Paulo Miranda
- Michael Douglas (Doug)
- Claro Henrique"""

[[teams]]
login = "teambrbr048"
nome = "Abacate Atômico"
foto = "teambrbr48.webp"
musica = "https://www.youtube.com/watch?v=ZUlAytznxn4"

[[teams]]
login = "teambrbr049"
nome = "Vamu vense"
foto = "teambrbr49.webp"
musica = "https://www.youtube.com/watch?v=IPXIgEAGe4U&t=12s"

[[teams]]
login = "teambrbr050"
nome = "man java"
musica = "https://www.youtube.com/watch?v=KXzFFUbCRSw&ab_channel=MatheusAndrade"
foto = "teambrbr50.webp"

[[teams]]
login = "teambrbr051"
nome = "Code Zwang"
foto = "teambrbr51.webp"

[[teams]]
login = "teambrbr052"
nome = "NP-Compeixe"
foto = "teambrbr52.webp"

[[teams]]
login = "teambrbr053"
nome = "Home Off C++"
foto = "teambrbr53.webp"

[[teams]]
login = "teambrbr054"
nome = "Code Distancing"
foto = "teambrbr54.webp"

[[teams]]
login = "teambrbr055"
nome = "Overclock"
musica = "https://www.youtube.com/watch?v=pHAQA8FJP3c"
foto = "teambrbr55.webp"

[[teams]]
login = "teambrbr056"
nome = "No Main No Gain"
foto = "teambrbr56.webp"

[[teams]]
login = "teambrbr057"
nome = "deitando no gramado"
foto = "teambrbr57.webp"
musica = "https://www.youtube.com/watch?v=WTJSt4wP2ME"

[[teams]]
login = "teambrbr058"
nome = "CPA - Carregados Pelo Alyson"
foto = "teambrbr58.webp"
musica = "https://youtu.be/M1n0s60dL44"

[[teams]]
login = "teambrbr059"
nome = "Bolonhesa"
foto = "teambrbr59.webp"
musica = "https://www.youtube.com/watch?v=XW0W7j04iRQ"

[[teams]]
login = "teambrbr060"
nome = "S -> aSa | a"
foto = "teambrbr60.webp"
musica = "https://www.youtube.com/watch?v=EtrodNQKZ8I"

[[teams]]
login = "teambrbr061"
nome = "Alquimistas"
musica = "https://www.youtube.com/watch?v=0y1kGcMi_l8"
foto = "teambrbr61.webp"

[[teams]]
login = "teambrbr062"
nome = "seila"
foto = "teambrbr62.webp"

[[teams]]
login = "teambrbr063"
nome = "The droids you are looking for"
foto = "teambrbr63.webp"

[[teams]]
login = "teambrbr064"
nome = "Conexão Tucuju: aqui o caixeiro chegou de barco"
foto = "teambrbr64.webp"

