[[teams]]
login="arq1"
nome="Nome do Config"
foto="KLM.png"
musica="https://youtu.be/gdG4xbU8cZo"
comentario="Na foto: Prof. Acauan (Coach), Markus Kaul, Leandro Schillreff, Miller Raycell"

[[teams]]
login="teambrsp066"
nome="Time Fake"
foto="fake.png"
musica="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
comentario="Este time e' falso, mas a musica e' legal"
