[[teams]]
login = "teambrrr001"
nome = "KLM"
foto = "teambrbr02.webp"
musica= "https://youtu.be/gdG4xbU8cZo"
comentario = "Na foto: Prof. Acauan (Coach), Markus Kaul, Leandro Schillreff, Miller Raycell"

[[teams]]
login="teambrsp066"
nome="Time Fake"
foto="fake.png"
musica="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
comentario="Este time e' falso, mas a musica e' legal"

[[teams]]
login = "teambrbr01"
nome = "Hoje tem AC do Ribamar"
foto = "teambrbr01.webp"

[[teams]]
login = "teambrbr02"
nome = "KLM"
foto = "teambrbr02.webp"
musica= "https://youtu.be/gdG4xbU8cZo"
comentario = "Na foto: Prof. Acauan (Coach), Markus Kaul, Leandro Schillreff, Miller Raycell"

[[teams]]
login = "teambrbr03"
nome = "Vêm tranquilo, afoba não"
foto = "teambrbr03.webp"

[[teams]]
login = "teambrbr04"
nome = "cuscuz com cachaça"
musica = "https://www.youtube.com/watch?v=GqutEnlLX6o"
foto = "teambrbr04.webp"
comentario = "sim"

[[teams]]
login = "teambrbr05"
nome = "Os k-ésimos"
foto = "teambrbr05.webp"

[[teams]]
login = "teambrbr06"
nome = "Xerebêlerebébis"
musica = "https://www.youtube.com/watch?v=GsFlbMS7UIc"
foto = "teambrbr06.webp"

[[teams]]
login = "teambrbr07"
nome = "Que bixiga é essa?"
musica = "https://www.youtube.com/watch?v=hIRRx5hYK34"
foto = "teambrbr07.webp"

[[teams]]
login = "teambrbr08"
nome = "UnespRPM"
foto = "teambrbr08.webp"

[[teams]]
login = "teambrbr09"
nome = "anarquia às 8"
foto = "teambrbr09.webp"

[[teams]]
login = "teambrbr10"
nome = "Você é fraco, te falta O(1)"
foto = "teambrbr10.webp"

[[teams]]
login = "teambrbr11"
nome = "AC(¬‿¬)WA"
foto = "teambrbr11.webp"

[[teams]]
login = "teambrbr12"
nome = "Monkeys"
musica = "https://youtu.be/rBSfI10pXHM"
foto = "teambrbr12.webp"

[[teams]]
login = "teambrbr13"
nome = "União Fiasco"
foto = "teambrbr13.webp"

[[teams]]
login = "teambrbr14"
nome = "Sem TLE irmão"
foto = "teambrbr14.webp"

[[teams]]
login = "teambrbr15"
nome = "NP-Lúcia"
foto = "teambrbr15.webp"

[[teams]]
login = "teambrbr16"
nome = "Mews Lovers"
musica = "https://www.youtube.com/watch?v=Akzba3ubOmI"
foto = "teambrbr16.webp"
comentario = "Após anos de hegemonia com um time imbatível, Weiss e Felipera embarcam em uma nova missão ao lado de Gasparini."

[[teams]]
login = "teambrbr17"
nome = "Wrong Answer 1000%"
foto = "teambrbr17.webp"

[[teams]]
login = "teambrbr18"
nome = "UFMA Time 1"
foto = "teambrbr18.webp"

[[teams]]
login = "teambrbr19"
nome = "EM3.1415NA"
musica = "https://youtu.be/A_EWrzI2CUg"
foto = "teambrbr19.webp"

[[teams]]
login = "teambrbr20"
nome = "Três caras numa moto"
foto = "teambrbr20.webp"

[[teams]]
login = "teambrbr21"
nome = "Programadores: continue"
musica = "https://youtu.be/AYlvRQhYGS4"
foto = "teambrbr21.webp"

[[teams]]
login = "teambrbr22"
nome = "KondZhiLa"
musica = "https://www.youtube.com/watch?v=yQ8xJHuW7TY"
foto = "teambrbr22.webp"

[[teams]]
login = "teambrbr23"
nome = "[nome_do_time]"
foto = "teambrbr23.webp"

[[teams]]
login = "teambrbr24"
nome = "Dorime"
foto = "teambrbr24.webp"

[[teams]]
login = "teambrbr25"
nome = "Qual o nome do time?"
foto = "teambrbr25.webp"

[[teams]]
login = "teambrbr26"
nome = "namae wa??"
musica = "https://www.youtube.com/watch?v=zcL74R3akrk"
foto = "teambrbr26.webp"

[[teams]]
login = "teambrbr27"
nome = "vae victis"
foto = "teambrbr27.webp"

[[teams]]
login = "teambrbr28"
nome = "Quero café"
foto = "teambrbr28.webp"

[[teams]]
login = "teambrbr29"
nome = "O amarelo é impostor"
musica = "https://www.youtube.com/watch?v=qv7LYwC7a4c"
foto = "teambrbr29.webp"

[[teams]]
login = "teambrbr30"
nome = "$wa"
musica = "https://drive.google.com/file/d/1pfyjFWrcNHq6cdk2jtGK6l4xMLUdjWEd/view?usp=sharing"
foto = "teambrbr30.webp"
comentario = "Estamos enviando a música via drive. Se precisar que faça o upload em outra plataforma podemos fazer. Feita com muito carinho, por favor se esforcem para nos encaixar em algum prêmio com música. Brincadeira rs, um abraço."

[[teams]]
login = "teambrbr31"
nome = "GTA: Grover's Street Algorithms"
foto = "teambrbr31.webp"

[[teams]]
login = "teambrbr32"
nome = "O(f*ck)"
foto = "teambrbr32.webp"

[[teams]]
login = "teambrbr33"
nome = "A query tá on"
foto = "teambrbr33.webp"

[[teams]]
login = "teambrbr34"
nome = "Rock Lee Casado Não Vai + Pra Pagode"
foto = "teambrbr34.webp"

[[teams]]
login = "teambrbr35"
nome = "GGG"
foto = "teambrbr35.webp"

[[teams]]
login = "teambrbr36"
nome = "Beto was ejected"
foto = "teambrbr36.webp"

[[teams]]
login = "teambrbr37"
nome = "YouShallNot.stay"
foto = "teambrbr37.webp"

[[teams]]
login = "teambrbr38"
nome = "RGB IFSP-ARQ Team"
musica = "https://www.youtube.com/watch?v=xAM51Ovpr9M"
foto = "teambrbr38.webp"

[[teams]]
login = "teambrbr39"
nome = "Amigos da Aracele"
musica = "https://www.youtube.com/watch?v=XusBJ8ADSH8"
foto = "teambrbr39.webp"

[[teams]]
login = "teambrbr40"
nome = "PD pá"
foto = "teambrbr40.webp"

[[teams]]
login = "teambrbr41"
nome = "Bagre Branco, Branco Bagre"
foto = "teambrbr41.webp"

[[teams]]
login = "teambrbr42"
nome = "WA em O(1)"
foto = "teambrbr42.webp"

[[teams]]
login = "teambrbr43"
nome = "BalloonField"
foto = "teambrbr43.webp"

[[teams]]
login = "teambrbr44"
nome = "2 matemáticos e 2 flamenguistas"
musica = "https://www.youtube.com/watch?v=kDs_P1ek5cE"
foto = "teambrbr44.webp"

[[teams]]
login = "teambrbr45"
nome = "Mensageiros do à main"
foto = "teambrbr45.webp"

[[teams]]
login = "teambrbr46"
nome = "Que time?"
foto = "teambrbr46.webp"

[[teams]]
login = "teambrbr47"
nome = ":ultra_fast_parrot:"
musica = "https://www.youtube.com/watch?v=kAdbOO6xWkc"
foto = "teambrbr47.webp"
comentario = """De cima para baixo e da esquerda para direita na foto:
- Prof. Wladimir Tavares
- Paulo Miranda
- Michael Douglas (Doug)
- Claro Henrique"""

[[teams]]
login = "teambrbr48"
nome = "Abacate Atômico"
foto = "teambrbr48.webp"

[[teams]]
login = "teambrbr49"
nome = "Vamu vense"
foto = "teambrbr49.webp"

[[teams]]
login = "teambrbr50"
nome = "man java"
musica = "https://www.youtube.com/watch?v=KXzFFUbCRSw&ab_channel=MatheusAndrade"
foto = "teambrbr50.webp"

[[teams]]
login = "teambrbr51"
nome = "Code Zwang"
foto = "teambrbr51.webp"

[[teams]]
login = "teambrbr52"
nome = "NP-Compeixe"
foto = "teambrbr52.webp"

[[teams]]
login = "teambrbr53"
nome = "Home Off C++"
foto = "teambrbr53.webp"

[[teams]]
login = "teambrbr54"
nome = "Code Distancing"
foto = "teambrbr54.webp"

[[teams]]
login = "teambrbr55"
nome = "Overclock"
musica = "https://www.youtube.com/watch?v=pHAQA8FJP3c"
foto = "teambrbr55.webp"

[[teams]]
login = "teambrbr56"
nome = "No Main No Gain"
foto = "teambrbr56.webp"

[[teams]]
login = "teambrbr57"
nome = "deitando no gramado"
foto = "teambrbr57.webp"

[[teams]]
login = "teambrbr58"
nome = "CPA - Carregados Pelo Alyson"
foto = "teambrbr58.webp"

[[teams]]
login = "teambrbr59"
nome = "Bolonhesa"
foto = "teambrbr59.webp"

[[teams]]
login = "teambrbr60"
nome = "S -> aSa | a"
foto = "teambrbr60.webp"

[[teams]]
login = "teambrbr61"
nome = "Alquimistas"
musica = "https://www.youtube.com/watch?v=0y1kGcMi_l8"
foto = "teambrbr61.webp"

[[teams]]
login = "teambrbr62"
nome = "seila"
foto = "teambrbr62.webp"

[[teams]]
login = "teambrbr63"
nome = "The droids you are looking for"
foto = "teambrbr63.webp"

[[teams]]
login = "teambrbr64"
nome = "Conexão Tucuju: aqui o caixeiro chegou de barco"
foto = "teambrbr64.webp"

